name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build all platforms and run integration tests
        run: |
          make all integration

      - name: Run cargo
        run: |
          cd degpt
          cargo build
